name: CI

on:
  pull_request:
    branches: [ main ]

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  GCC-Build:
    timeout-minutes: 45
    env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
        HOMEBREW_NO_ANALYTICS: 1

    strategy:
        fail-fast: false
        matrix:
            os: [ ubuntu-latest, macos-11 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install macOS software
      if: matrix.os == 'macos-11'
      run: |
        set -x
        brew install gnu-tar make texinfo
        # Homebrew prefix is different for x86-64 and aarch64.
        export HOMEBREW_PREFIX=/usr/local
        # Put Homebrew installed make, and tar first in PATH so "make"
        # is version 4.x and "tar" is GNU tar.
        echo "export PATH=$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH" >> ~/.profile
        echo "export PATH=$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH" >> ~/.bashrc
    - name: Install Linux software
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends texinfo

    - name: Build MSP430-gcc
      run: |
        # Ensure GNU tar is first in path on macOS.
        [ "$(uname)" = "Linux" ] || source ~/.bashrc
        git clone --depth 1 --single-branch --branch develop https://github.com/contiki-ng/contiki-ng
        cd contiki-ng
        perl -pi -e 's#-j20#-j6#g' tools/toolchain/msp430/buildmsp.sh
        perl -pi -e 's# CFLAGS="-g"##g' tools/toolchain/msp430/buildmsp.sh
        perl -pi -e 's#/usr/local/stow.*$#/tmp/mspgcc-4.7.4"#g' tools/toolchain/msp430/buildmsp.sh
        perl -pi -e 's#http://ftpmirror.gnu.org#https://ftp.sunet.se/mirror/gnu.org/gnu#g' tools/toolchain/msp430/buildmsp.sh
        mkdir -p /tmp/mspgcc-4.7.4
        # No -print-multi-os-directory on Clang/macOS.
        [ "$(uname)" = "Linux" ] || perl -pi -e 's#^mkdir gcc-4.7.4-msp430#mkdir gcc-4.7.4-msp430\nperl -pi -e "s\#^MULTIOSDIR.*\#MULTIOSDIR=../lib\#g" binutils-2.22/libiberty/Makefile.in#g' tools/toolchain/msp430/buildmsp.sh
        # Cannot determine executable suffix on macOS.
        perl -pi -e 's#^./contrib/download_prerequisites#./contrib/download_prerequisites\nperl -pi -e "s\#^for i in \.exe\#gmp_cv_prog_exeext_for_build=""; for i in \.exe\#g" gmp/configure#g' tools/toolchain/msp430/buildmsp.sh
        # Misdetection of K&R compiler on macOS.
        perl -pi -e 's#^./contrib/download_prerequisites#./contrib/download_prerequisites\nperl -pi -e "s\#U_FOR_BUILD=_\#U_FOR_BUILD=\#g" gmp/configure#g' tools/toolchain/msp430/buildmsp.sh
        # CC_FOR_BUILD in GMP is detected as broken, default to working.
        perl -pi -e 's#^./contrib/download_prerequisites#./contrib/download_prerequisites\nperl -pi -e "s\#^cc_for_build_works=no\#cc_for_build_works=yes\#g" */configure */*/configure#g' tools/toolchain/msp430/buildmsp.sh
        #perl -pi -e 's#^./contrib/download_prerequisites#perl -pi -e "s\#gmp-4.3.2\#gmp-5.1.3\#g" contrib/download_prerequisites\n./contrib/download_prerequisites#g' tools/toolchain/msp430/buildmsp.sh
        #perl -pi -e 's#^./contrib/download_prerequisites#perl -pi -e "s\#wget ftp://gcc.gnu.org/pub/gcc/infrastructure/.GMP.tar.bz2\#wget https://ftp.gnu.org/gnu/gmp/gmp-5.1.3.tar.bz2\#g" contrib/download_prerequisites\n./contrib/download_prerequisites#g' tools/toolchain/msp430/buildmsp.sh
        #perl -pi -e 's#^./contrib/download_prerequisites#perl -pi -e "s\#mpfr-2.4.2\#mpfr-4.1.1\#g" contrib/download_prerequisites\n./contrib/download_prerequisites#g' tools/toolchain/msp430/buildmsp.sh
        #perl -pi -e 's#^./contrib/download_prerequisites#perl -pi -e "s\#wget ftp://gcc.gnu.org/pub/gcc/infrastructure/.MPFR.tar.bz2\#wget https://ftp.gnu.org/gnu/mpfr/mpfr-4.1.1.tar.bz2\#g" contrib/download_prerequisites\n./contrib/download_prerequisites#g' tools/toolchain/msp430/buildmsp.sh
        #perl -pi -e 's#^./contrib/download_prerequisites#perl -pi -e "s\#mpc-0.8.1\#mpc-1.2.1\#g" contrib/download_prerequisites\n./contrib/download_prerequisites#g' tools/toolchain/msp430/buildmsp.sh
        #perl -pi -e 's#^./contrib/download_prerequisites#perl -pi -e "s\#wget ftp://gcc.gnu.org/pub/gcc/infrastructure/.MPC.tar.gz\#wget https://ftp.gnu.org/gnu/mpc/mpc-1.2.1.tar.gz\#g" contrib/download_prerequisites\n./contrib/download_prerequisites#g' tools/toolchain/msp430/buildmsp.sh
        tools/toolchain/msp430/buildmsp.sh
        HERE=`pwd`
        (cd /tmp && tar cjf $HERE/mspgcc-${{ matrix.os }}.tar.bz2 mspgcc-4.7.4)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mspgcc-${{ matrix.os }}
        path: contiki-ng/mspgcc-${{ matrix.os }}.tar.bz2
        retention-days: 5
